[package]
name = "chapter_2"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"  #rand kullanacaksan 0.9.2 yap
# rand crate'i rastgele sayılar üretmek için kullanılır. Bu, oyunun rastgele bir sayı seçmesini sağlar.
